"""
consolidate.py — one-time migration: copy all books to ~/Books/ (flat folder).

Sources: books-inventory.csv generated by the earlier full-home scan.
Deduplication: files with the same basename + size_mb are considered identical;
  only the highest-priority copy is kept.
Safety: COPY only, never move or delete originals.

Usage:
  python consolidate.py [--dry-run] [--skip-likely]
"""
import csv
import os
import re
import sys
import shutil
from pathlib import Path
from collections import defaultdict

INVENTORY = Path.home() / "conductor/workspaces/conductor-dev/ottawa/.context/mac-organization/books-inventory.csv"
BOOKS_DIR = Path(os.environ.get("BOOKS_DIR", Path.home() / "Books"))

DRY_RUN     = "--dry-run"    in sys.argv
SKIP_LIKELY = "--skip-likely" in sys.argv

BOOK_EXTS = {".pdf", ".epub", ".mobi", ".azw3", ".azw", ".djvu", ".cbz", ".cbr"}


def source_priority(path: str) -> int:
    """Lower = preferred source when deduplicating."""
    p = path.lower()
    if "/calibre library/" in p:                   return 0
    if "cloudStorage/dropbox/books" in p:           return 1
    if "mobile documents" in p and "/books/" in p:  return 2
    if "/documents/books" in p:                     return 3
    if "/documents/" in p:                          return 4
    if "cloudStorage/dropbox" in p:                 return 5
    if "mobile documents" in p:                     return 6
    if "/downloads/" in p:                          return 7
    if "/devprojects/" in p:                        return 8
    return 9


def safe_dest_name(filename: str, books_dir: Path) -> str:
    """Return a filename that doesn't collide in books_dir."""
    dest = books_dir / filename
    if not dest.exists():
        return filename
    # Same file already there?
    src_size = None  # checked by caller
    stem, ext = Path(filename).stem, Path(filename).suffix
    for n in range(1, 100):
        candidate = f"{stem}_{n}{ext}"
        if not (books_dir / candidate).exists():
            return candidate
    return filename  # give up, will overwrite


def main():
    if not INVENTORY.exists():
        print(f"ERROR: inventory not found at {INVENTORY}")
        sys.exit(1)

    BOOKS_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Target folder : {BOOKS_DIR}")
    print(f"Dry run       : {DRY_RUN}")
    print(f"Skip likely   : {SKIP_LIKELY}")
    print()

    # Load inventory
    rows = []
    with open(INVENTORY, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["kind"] not in ("book", "likely-book"):
                continue
            if SKIP_LIKELY and r["kind"] == "likely-book":
                continue
            ext = Path(r["path"]).suffix.lower()
            if ext not in BOOK_EXTS:
                continue
            rows.append(r)

    print(f"Inventory rows to process: {len(rows)}")

    # Deduplicate: keep best copy per (basename_lower, size_mb)
    groups: dict[tuple, list] = defaultdict(list)
    for r in rows:
        key = (Path(r["path"]).name.lower(), r["size_mb"])
        groups[key].append(r)

    winners = []
    for key, copies in groups.items():
        best = min(copies, key=lambda r: source_priority(r["path"]))
        winners.append(best)

    print(f"Unique books after dedup : {len(winners)}")
    print(f"Redundant copies skipped : {len(rows) - len(winners)}")
    print()

    copied = skipped_exists = skipped_missing = errors = 0

    for i, r in enumerate(winners, 1):
        src_path = Path(os.path.expanduser(r["path"]))

        if not src_path.exists():
            skipped_missing += 1
            if i % 500 == 0 or i == len(winners):
                _progress(i, len(winners), copied, skipped_missing, errors)
            continue

        dest_name = safe_dest_name(src_path.name, BOOKS_DIR)
        dest_path = BOOKS_DIR / dest_name

        # Skip if already there with same size
        if dest_path.exists() and dest_path.stat().st_size == src_path.stat().st_size:
            skipped_exists += 1
            if i % 500 == 0 or i == len(winners):
                _progress(i, len(winners), copied, skipped_missing, errors)
            continue

        if DRY_RUN:
            print(f"  [dry] {src_path.name}  →  {BOOKS_DIR}/{dest_name}")
            copied += 1
        else:
            try:
                shutil.copy2(src_path, dest_path)
                copied += 1
            except Exception as e:
                print(f"  ERROR copying {src_path.name}: {e}")
                errors += 1

        if i % 100 == 0 or i == len(winners):
            _progress(i, len(winners), copied, skipped_missing, errors)

    print()
    print("─" * 60)
    print(f"Copied          : {copied}")
    print(f"Already in dest : {skipped_exists}")
    print(f"Not on disk     : {skipped_missing}  (cloud files not downloaded)")
    print(f"Errors          : {errors}")
    print()
    if not DRY_RUN:
        print(f"Next: cd ~/DevProjects/BookShelf && python scanner.py")


def _progress(i, total, copied, missing, errors):
    pct = i * 100 // total
    print(f"  [{pct:3d}%] {i}/{total}  copied={copied}  cloud-missing={missing}  errors={errors}")


if __name__ == "__main__":
    main()
